<?php
    session_start();
    include "dbmanager.php";
    if(isset($_SESSION['username'])){

        $username = $_SESSION['username'];
        $db = new dbmanager();
        $con=$db->dbConnection();
        $dp=$_SESSION['dp'];
        $row = $db->postData($con,$_GET['postid']);
        $commentRow = $db->commentData($con,$_GET['postid']);
        if(isset($_POST['liked'])){
            $postid = $_POST['postid'];
            $db->writeLikeData($con,$username,$postid);
            $_POST['liked'] = FALSE;
        }
        if(isset($_POST['unliked'])){
            $postid = $_POST['postid'];
            $db->deleteLikeData($con,$username,$postid);
            $_POST['unliked'] = FALSE;
        }
        if(isset($_POST['usercomment']) && $_POST['commentbtn']){
            $usercomment = $_POST['usercomment'];
            $db->writeUserComment($con,$username,$_GET['postid'],$usercomment);
        }
    }else{
        header('Location:index.php');
        die();
    }
?>
<!doctype html>
<html lang="en">


  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- My CSS LINK -->
    <link rel="stylesheet" type="text/css" href="css/comment.css">
    <title></title>
    <!-- Adding jquery-->
    <script src="js/jquery-3.3.1.min.js"></script>
    <!--My JavaScript-->
    <script type="text/JavaScript" src="js/comment.js"></script>
  </head>


  <body>

    <!-- Navbar Start-->
    <nav class="navbar navbar-expand-md bg-dark navbar-dark sticky-top">
      
      <!-- Button For Toggling Navbar -->
      <button class="navbar-toggler" data-toggle="collapse" data-target="#target">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Username and Navbar profile picture generated by php -->
      <span class="navbar-text ml-auto">
          <a href="profile.php">
          <?php echo $username; ?>
          </a>
      </span>
      <a class="navbar-brand "><img id="userImage" src="image/avatar/smoke.png" alt="smoke" width="50px" height="50px"></a>

      <!-- Wrapping the collapse items inside a div -->
      <div class="collapse navbar-collapse" id="target">

        <!-- Search Bar and Search button -->
        <form class="form-inline ml-auto" action="searchusers.php" method="get">
          <input class="form-control mr-sm-2" name="searchkey" type="search" placeholder="Search" aria-label="Search">
          <button type="btn btn-light my-sm-0" type="submit">Search</button>
        </form>

        <!-- Link List -->
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a href="newsfeed.php" class="nav-link">Pending request</a>
            </li>
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item">
            <a href="newsfeed.php" class="nav-link">NewsFeed</a>
          </li>
        </ul>
        <ul class="navbar-nav ">
          <li class="nav-item">
            <a class="nav-link">Strategy</a>
          </li>
        </ul>
        <ul class="navbar-nav d-block d-sm-block d-md-none">
          <li class="nav-item">
            <a class="nav-link">Friend List</a>
          </li>
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item">
            <a href="logoutprocess.php" class="nav-link">Logout</a>
          </li>
        </ul>
        <!-- End List -->

      </div>
      <!-- End Div -->

    </nav>
    <!-- End Nav -->


    <!-- This div containes The POST-->
    <div class="mx-auto col-md-8 bg-dark text-light" id="container1">

        <!-- Post Div -->
        <div class="container-fluid" id="postdiv">
            <div class="container-fluid indpost">

                <!-- Username and time -->
                <div class="row p-1">
                    <div class="col-sm-9 nametime">
                        <h5><?php echo $row['username'];?></h5>
                    </div>
                    <div class="col-sm-3 nametime">
                        <small>Date:<?php echo $row['postdate'];?> Time:<?php echo $row['posttime'];?> </small>
                    </div>
                </div>
                <!-- End of  username and time -->

                <!-- Post content -->
                <div class="row p-1 postcontent">
                    <p><?php echo $row['post'];?></p>
                </div>

                <!-- Buttons for like shere and comment -->
                <div class="row p-1">
                    <div class="col-xs-10">
                        <?php
                            if($db->isLiked($con,$username,$_GET['postid'])){
                                echo "<button  name=\"like\" class=\"btn btn-success ".$row['postid']." unlike\">Unlike</button>";
                            }else{
                                echo "<button  name=\"like\" class=\"btn btn-success ".$row['postid']." like\">Like</button>";
                            }
                        ?>

                    </div>
                </div>

            </div>

            <div>
              <h3>Comments</h3> 
            </div>

            <?php
                for($i=0;$i<count($commentRow);$i++){
                    echo "<div class=\"row\">
                            <div class=\"container-fluid\">
                              <div class=\"row\">
                                <div class=\"col-sm-9\">
                                    <h5>".$commentRow[$i][1]."</h5>
                                </div>
                                <div class=\"col-sm-3\">
                                    <small>Date:".$commentRow[$i][4]."  Time:".$commentRow[$i][5]." </small>
                                </div>
                              </div>
                              <div class=\" comment\">
                                ".$commentRow[$i][2]."
                              </div>
                            </div>
                        </div>";
                }
            ?>

            <div class="row-12">
              <div class="form-horizontal">
                <div class="col-sm-12 mb-3">
                  <h6 class="mt-3">Write your comment</h6>
                  <textarea class="form-control" id="usercomment" placeholder="Write your Comment"></textarea>
                </div>
                <div class="col-sm-1 mb-3">
                  <button id="commentbtn" class="btn btn-info">Comment</button>
                </div>
              </div>
            </div>


        </div>
        <!-- End of Post Div-->

    </div>
    <!-- End of div containing all post, image and buttons -->


    <!-- Optional JavaScript -->
    <!-- Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>