<?php
    include 'profileprocess.php';
?>
<!doctype html>
<html lang="en">


  <head>


    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- My CSS LINK -->
    <link rel="stylesheet" type="text/css" href="css/profile.css">
    <title>NewsFeed!</title>
    <!-- Adding jquery-->
    <script src="js/jquery-3.3.1.min.js"></script>
    <!--My JavaScript-->
    <script type="text/JavaScript" src="js/profile.js"></script>
  </head>


  <body>

    <!-- Navbar Start-->
    <nav class="navbar navbar-expand-md bg-dark navbar-dark sticky-top">
      
      <!-- Button For Toggling Navbar -->
      <button class="navbar-toggler" data-toggle="collapse" data-target="#target">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Username and Navbar profile picture generated by php -->
      <span class="navbar-text ml-auto">
          <a href="profile.php">
              <?php
                echo $username;
              ?>
          </a>
      </span>
      <a class="navbar-brand "><img id="userImage" src="image/avatar/<?php echo $dp?>.png" alt="smoke" width="50px" height="50px"></a>

      <!-- Wrapping the collapse items inside a div -->
      <div class="collapse navbar-collapse" id="target">

        <!-- Search Bar and Search button -->
        <form class="form-inline ml-auto" action="searchusers.php" method="post">
          <input class="form-control mr-sm-2" name = "searchkey" type="search" placeholder="Search" aria-label="Search">
          <button type="btn btn-light my-sm-0" type="submit">Search</button>
        </form>

        <!-- Link List -->
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a href="newsfeed.php" class="nav-link">Newsfeed</a>
          </li>
        </ul>
        <ul class="navbar-nav ">
          <li class="nav-item">
            <a class="nav-link">Strategy</a>
          </li>
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item">
            <a href="logoutprocess.php" class="nav-link">Logout</a>
          </li>
        </ul>
        <!-- End List -->

      </div>
      <!-- End Div -->

    </nav>
    <!-- End Nav -->







    <!-- This div containes all post, image and buttons -->
    <div class="mx-auto col-sm-10 bg-dark text-light" id="container1">

      <!-- Profile Picture -->
      <img src="image/avatar/<?php echo $dp?>.png" width="200px" height="200px" alt="Smoke" class="img-thumbnail mx-auto d-block" id="profilePic">

      <!-- Tab Div -->
      <div class="container-fluid">

        <div class="row">
          <div class="col text-center tabcol">
            Pictures
          </div>
          <div onclick="redirectMyProfile()" class="col text-center tabcol">
            Edit Profile
          </div>
        </div>

      </div>
      <!-- Tab Div End -->
      
      


      <!-- Post Div -->
      <div class="container-fluid" id="postdiv">

        <div class="container-fluid">
          <div class="row">

              <h3><b>
                    <?php
                        if(count($row)==0){
                            echo "You have no post";
                        }else{
                            echo "Your post";
                        }
                    ?>
              </b></h3>
          </div>
        </div>





        <?php
            for($i=0;$i<count($row);$i++){
                $indPost = "";
                if($db->isLiked($con,$username,$row[$i][0])){
                    $indPost = "

                        <!-- This is a indevidual post-->
                        <div class=\"container-fluid indpost\">
                
                          <!-- Username and time -->
                          <div class=\"row p-1\">
                            <div class=\"col-sm-9 nametime\">
                              <h5>".$row[$i][1]."</h5>
                            </div>
                            <div class=\"col-sm-3 nametime\">
                              <small>Date: ".$row[$i][3]." Time: ".$row[$i][4]."</small>
                            </div>
                          </div>
                          <!-- End of  username and time -->
                
                          <!-- Post content -->
                          <div class=\"row p-1 postcontent\">
                            <p>".$row[$i][2]."
                            </p>
                          </div>
                          
                          <!-- Buttons for like shere and comment -->
                          <div class=\"row p-1\">
                            <div class=\"col-xs-10\">
                                <button  name=\"like\" class=\"btn btn-success ".$row[$i][0]." unlike\">Unlike</button>
                                <button  name=\"comment\" class=\"btn btn-warning ".$row[$i][0]." comment\">Comment</button>
                            </div>
                            <div class=\"col-xs-2 ml-auto\">
                               <button name=\"deletepost\" class = \"btn btn-danger ".$row[$i][0]." delete\">Delete Post</button>
                            </div>
                          </div>
                        
                        </div>
                        <!-- End of indi Post-->";


                }else{

                    $indPost = "

                        <!-- This is a indevidual post-->
                        <div class=\"container-fluid indpost\">
                
                          <!-- Username and time -->
                          <div class=\"row p-1\">
                            <div class=\"col-sm-9 nametime\">
                              <h5>".$row[$i][1]."</h5>
                            </div>
                            <div class=\"col-sm-3 nametime\">
                              <small>Date: ".$row[$i][3]." Time: ".$row[$i][4]."</small>
                            </div>
                          </div>
                          <!-- End of  username and time -->
                
                          <!-- Post content -->
                          <div class=\"row p-1 postcontent\">
                            <p>".$row[$i][2]."
                            </p>
                          </div>
                          
                          <!-- Buttons for like shere and comment -->
                          <div class=\"row p-1\">
                            <div class=\"col-xs-10\">
                                <button  name=\"like\" class=\"btn btn-success ".$row[$i][0]." like\">Like</button>
                                <button  name=\"comment\" class=\"btn btn-warning ".$row[$i][0]." comment\">Comment</button>
                            </div>
                            <div class=\"col-xs-2 ml-auto\">
                               <button name=\"deletepost\" class = \"btn btn-danger ".$row[$i][0]." delete \">Delete Post</button>
                            </div>
                          </div>
                        
                        </div>
                        <!-- End of indi Post-->";

                }
                
                echo $indPost;
            }
        ?>

        

      
      </div>
      <!-- End of Post Div-->






    </div>
    <!-- End of div containing all post, image and buttons -->






    





    <!-- Optional JavaScript -->
    <!-- Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>