<?php
    include 'searchusersprocess.php';
?>
<!doctype html>
<html lang="en">


<head>


    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- My CSS LINK -->
    <link rel="stylesheet" type="text/css" href="css/profile.css">
    <title>NewsFeed!</title>
    <!-- Adding jquery-->
    <script src="js/jquery-3.3.1.min.js"></script>
    <!--My JavaScript-->
    <script type="text/JavaScript" src="js/profile.js"></script>
</head>


<body>

<!-- Navbar Start-->
<nav class="navbar navbar-expand-md bg-dark navbar-dark sticky-top">

    <!-- Button For Toggling Navbar -->
    <button class="navbar-toggler" data-toggle="collapse" data-target="#target">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Username and Navbar profile picture generated by php -->
    <span class="navbar-text ml-auto">
          <a href="profile.php">
              <?php
                echo $username;
              ?>
          </a>
      </span>
    <a class="navbar-brand "><img id="userImage" src="image/avatar/<?php echo $dp; ?>.png" alt="smoke" width="50px" height="50px"></a>

    <!-- Wrapping the collapse items inside a div -->
    <div class="collapse navbar-collapse" id="target">

        <!-- Search Bar and Search button -->
        <form class="form-inline ml-auto" action="searchusers.php" method="post">
            <input class="form-control mr-sm-2" name="searchkey" type="search" placeholder="Search" aria-label="Search">
            <button type="btn btn-light my-sm-0" type="submit">Search</button>
        </form>

        <!-- Link List -->
        
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a href="newsfeed.php" class="nav-link">Newsfeed</a>
            </li>
        </ul>
        <ul class="navbar-nav ">
            <li class="nav-item">
                <a class="nav-link">Strategy</a>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="logoutprocess.php" class="nav-link">Logout</a>
            </li>
        </ul>
        <!-- End List -->

    </div>
    <!-- End Div -->

</nav>
<!-- End Nav -->







<!-- This div image and buttons -->
<div class="mx-auto col-sm-10 bg-dark text-light" id="container1">

    <div class="container-fluid" id="postdiv">

        <div class="container-fluid">
            <div class="row">
                <?php

                    if(count($row)==0){
                        echo "<h3><b>No Users Found</b></h3>";
                    }elseif (count($row)==1 && $row[0][0]==$username){
                        echo "<h3><b>No Users Found</b></h3>";
                    }else{
                        echo "<h3><b>Users Found</b></h3>";
                    }
                ?>

            </div>
        </div>
        <?php
            for($i=0;$i<count($row);$i++){
                if($row[$i][0]==$username){
                    continue;
                }
                echo "<!-- This is a users container div-->
                        <div class=\"container-fluid\">
                            <!-- This is an indivisual user -->
                            <div class=\"row border border-white mt-2\">
                                <div class=\"col-5\">
                                    <img src=\"image/avatar/".$row[$i][3].".png\" width=\"50px\" height=\"50px\" alt=\"\">
                                </div>
                                <div class=\"col-7\">
                                    <a href=\"usersprofile.php?searchkey=".$row[$i][0]."\"><h5>".$row[$i][0]."</h5></a>
                                </div>
                            </div>
                            <!-- End of indi user-->
                        </div>
                        <!-- End of user container div-->";
            }
        ?>

    </div>







</div>
<!-- End of div containing all post, image and buttons -->












<!-- Optional JavaScript -->
<!-- Popper.js, then Bootstrap JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>